/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QrRouteImport } from './routes/qr'
import { Route as RecentActivityRouteImport } from './routes/recent-activity'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TimeDepositRouteImport } from './routes/time-deposit'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as QrMyRouteImport } from './routes/qr/my'
import { Route as QrScanRouteImport } from './routes/qr/scan'
import { Route as SettingsBiometricRouteImport } from './routes/settings/biometric'
import { Route as SettingsChangePasswordRouteImport } from './routes/settings/change-password'
import { Route as SettingsContactRouteImport } from './routes/settings/contact'
import { Route as SettingsFaqRouteImport } from './routes/settings/faq'
import { Route as SettingsLicensesRouteImport } from './routes/settings/licenses'
import { Route as SettingsPersonalRouteImport } from './routes/settings/personal'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsTermsRouteImport } from './routes/settings/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentActivityRoute = RecentActivityRouteImport.update({
  id: '/recent-activity',
  path: '/recent-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeDepositRoute = TimeDepositRouteImport.update({
  id: '/time-deposit',
  path: '/time-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const QrMyRoute = QrMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => QrRoute,
} as any)
const QrScanRoute = QrScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => QrRoute,
} as any)
const SettingsBiometricRoute = SettingsBiometricRouteImport.update({
  id: '/biometric',
  path: '/biometric',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChangePasswordRoute = SettingsChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsContactRoute = SettingsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFaqRoute = SettingsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLicensesRoute = SettingsLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPersonalRoute = SettingsPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTermsRoute = SettingsTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/qr': typeof QrRouteWithChildren
  '/recent-activity': typeof RecentActivityRoute
  '/register': typeof RegisterRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/time-deposit': typeof TimeDepositRoute
  '/transfer': typeof TransferRoute
  '/qr/my': typeof QrMyRoute
  '/qr/scan': typeof QrScanRoute
  '/settings/biometric': typeof SettingsBiometricRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/faq': typeof SettingsFaqRoute
  '/settings/licenses': typeof SettingsLicensesRoute
  '/settings/personal': typeof SettingsPersonalRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/qr': typeof QrRouteWithChildren
  '/recent-activity': typeof RecentActivityRoute
  '/register': typeof RegisterRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/time-deposit': typeof TimeDepositRoute
  '/transfer': typeof TransferRoute
  '/qr/my': typeof QrMyRoute
  '/qr/scan': typeof QrScanRoute
  '/settings/biometric': typeof SettingsBiometricRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/faq': typeof SettingsFaqRoute
  '/settings/licenses': typeof SettingsLicensesRoute
  '/settings/personal': typeof SettingsPersonalRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/qr': typeof QrRouteWithChildren
  '/recent-activity': typeof RecentActivityRoute
  '/register': typeof RegisterRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/time-deposit': typeof TimeDepositRoute
  '/transfer': typeof TransferRoute
  '/qr/my': typeof QrMyRoute
  '/qr/scan': typeof QrScanRoute
  '/settings/biometric': typeof SettingsBiometricRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/faq': typeof SettingsFaqRoute
  '/settings/licenses': typeof SettingsLicensesRoute
  '/settings/personal': typeof SettingsPersonalRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/loans'
    | '/login'
    | '/qr'
    | '/recent-activity'
    | '/register'
    | '/savings'
    | '/settings'
    | '/sitemap.xml'
    | '/time-deposit'
    | '/transfer'
    | '/qr/my'
    | '/qr/scan'
    | '/settings/biometric'
    | '/settings/change-password'
    | '/settings/contact'
    | '/settings/faq'
    | '/settings/licenses'
    | '/settings/personal'
    | '/settings/privacy'
    | '/settings/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/loans'
    | '/login'
    | '/qr'
    | '/recent-activity'
    | '/register'
    | '/savings'
    | '/settings'
    | '/sitemap.xml'
    | '/time-deposit'
    | '/transfer'
    | '/qr/my'
    | '/qr/scan'
    | '/settings/biometric'
    | '/settings/change-password'
    | '/settings/contact'
    | '/settings/faq'
    | '/settings/licenses'
    | '/settings/personal'
    | '/settings/privacy'
    | '/settings/terms'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/loans'
    | '/login'
    | '/qr'
    | '/recent-activity'
    | '/register'
    | '/savings'
    | '/settings'
    | '/sitemap.xml'
    | '/time-deposit'
    | '/transfer'
    | '/qr/my'
    | '/qr/scan'
    | '/settings/biometric'
    | '/settings/change-password'
    | '/settings/contact'
    | '/settings/faq'
    | '/settings/licenses'
    | '/settings/personal'
    | '/settings/privacy'
    | '/settings/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  QrRoute: typeof QrRouteWithChildren
  RecentActivityRoute: typeof RecentActivityRoute
  RegisterRoute: typeof RegisterRoute
  SavingsRoute: typeof SavingsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TimeDepositRoute: typeof TimeDepositRoute
  TransferRoute: typeof TransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent-activity': {
      id: '/recent-activity'
      path: '/recent-activity'
      fullPath: '/recent-activity'
      preLoaderRoute: typeof RecentActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-deposit': {
      id: '/time-deposit'
      path: '/time-deposit'
      fullPath: '/time-deposit'
      preLoaderRoute: typeof TimeDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/my': {
      id: '/qr/my'
      path: '/my'
      fullPath: '/qr/my'
      preLoaderRoute: typeof QrMyRouteImport
      parentRoute: typeof QrRoute
    }
    '/qr/scan': {
      id: '/qr/scan'
      path: '/scan'
      fullPath: '/qr/scan'
      preLoaderRoute: typeof QrScanRouteImport
      parentRoute: typeof QrRoute
    }
    '/settings/biometric': {
      id: '/settings/biometric'
      path: '/biometric'
      fullPath: '/settings/biometric'
      preLoaderRoute: typeof SettingsBiometricRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/change-password': {
      id: '/settings/change-password'
      path: '/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof SettingsChangePasswordRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/contact': {
      id: '/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof SettingsContactRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/faq': {
      id: '/settings/faq'
      path: '/faq'
      fullPath: '/settings/faq'
      preLoaderRoute: typeof SettingsFaqRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/licenses': {
      id: '/settings/licenses'
      path: '/licenses'
      fullPath: '/settings/licenses'
      preLoaderRoute: typeof SettingsLicensesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/personal': {
      id: '/settings/personal'
      path: '/personal'
      fullPath: '/settings/personal'
      preLoaderRoute: typeof SettingsPersonalRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/terms': {
      id: '/settings/terms'
      path: '/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof SettingsTermsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface QrRouteChildren {
  QrMyRoute: typeof QrMyRoute
  QrScanRoute: typeof QrScanRoute
}

const QrRouteChildren: QrRouteChildren = {
  QrMyRoute: QrMyRoute,
  QrScanRoute: QrScanRoute,
}

const QrRouteWithChildren = QrRoute._addFileChildren(QrRouteChildren)

interface SettingsRouteChildren {
  SettingsBiometricRoute: typeof SettingsBiometricRoute
  SettingsChangePasswordRoute: typeof SettingsChangePasswordRoute
  SettingsContactRoute: typeof SettingsContactRoute
  SettingsFaqRoute: typeof SettingsFaqRoute
  SettingsLicensesRoute: typeof SettingsLicensesRoute
  SettingsPersonalRoute: typeof SettingsPersonalRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsTermsRoute: typeof SettingsTermsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBiometricRoute: SettingsBiometricRoute,
  SettingsChangePasswordRoute: SettingsChangePasswordRoute,
  SettingsContactRoute: SettingsContactRoute,
  SettingsFaqRoute: SettingsFaqRoute,
  SettingsLicensesRoute: SettingsLicensesRoute,
  SettingsPersonalRoute: SettingsPersonalRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsTermsRoute: SettingsTermsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  QrRoute: QrRouteWithChildren,
  RecentActivityRoute: RecentActivityRoute,
  RegisterRoute: RegisterRoute,
  SavingsRoute: SavingsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TimeDepositRoute: TimeDepositRoute,
  TransferRoute: TransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
